import Head from 'next/head'
import { Inter } from '@next/font/google'
import ContactForm from "@/components/contact-component";
import APropos from "@/components/a-propos-component";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Marie-Laure</title>
                <meta name="description" content="Generated by create next app"/>
               
            </Head>
            <header className='p-[5vw] h-screen border-b border-solid border-black flex items-center justify-center'>
                <div className="px-[2vw] h-full flex justify-center items-center w-full relative">
                    <div className="wrapper">
                        <h2 className="lg:text-8xl lg:mr-40 sm:text-6xl sm:mr-20 mr-10 text-4xl  ">Marie-Laure</h2>
                        <h1 className="lg:text-4xl sm:text-2xl text-base italic absolute font-times">Développeuse web</h1>
                        <h2 className="lg:text-8xl sm:text-6xl text-4xl text-end">Edjour</h2>
                    </div>
                </div>
                <div className="scroll absolute bottom-[10px] h-[50px]">
                    <span className='absolute'>scroll</span>
                </div>
            </header>

            <section className="about-us-area border-b border-solid border-black lg:min-h-screen  min-h-[500px]  h-fit sm:grid grid-cols-home-grid block">
                <div className="title-section-home ">
                    <h3>A propos</h3>
                </div>
                <div className="flex">
                    <div className="lg:w-2/3 border-r border-dashed border-black sm:py-[5vw] py-[80px] sm:px-[50px] px-[20px] flex flex-col justify-center w-full">
                        <h3 className="title-section-home-mobile">A propos</h3>
                        <APropos/>
                    </div>
                    {/* <div className="w-1/3 bg-[url('../public/img/6.jpg')] bg-cover bg-center w-[30%] h-full lg:block hidden"></div> */}
                </div>
            </section>
            
            <section className="projets-area border-b border-solid border-black lg:min-h-screen min-h-[500px] h-fit sm:grid grid-cols-home-grid-reverse block sm:pt-0 pt-[80px]">
                <h3 className="title-section-home-mobile-reverse mr-[20px]">Projets</h3>
                    
                <div className="w-full h-full grid sm:grid-cols-10 sm:grid-rows-10 grid-cols-2 grid-rows-3 gap-px bg-black min-h-[500px] sm:mt-0 mt-10">
                    <div className="projet sm:col-start-1 sm:col-end-4 sm:row-start-1 sm:row-end-6 overflow-hidden flex items-center justify-center relative hoverable-text" data-text="projet1">
                        <img src="./img/works/1.jpg" alt="" className="object-cover object-center h-full w-full absolute"/>
                    </div>
                    <div className="projet sm:col-start-4 sm:col-end-8 sm:row-start-1 sm:row-end-7 overflow-hidden flex items-center justify-center relative hoverable-text" data-text="projet2">
                        <img src="./img/works/2.jpg" alt="" className="object-cover object-center h-full w-full absolute"/>
                    </div>
                    <div className="projet sm:col-start-8 sm:col-end-11 sm:row-start-1 sm:row-end-6 overflow-hidden flex items-center justify-center relative hoverable-text" data-text="projet3">
                        <img src="./img/works/3.jpg" alt="" className="object-cover object-center h-full w-full absolute"/>
                    </div>
                    <div className="projet sm:col-start-1 sm:col-end-4 sm:row-start-6 sm:row-end-[11] overflow-hidden flex items-center justify-center relative hoverable-text" data-text="projet4">
                        <img src="./img/works/4.jpg" alt="" className="object-cover object-center h-full w-full absolute"/>
                    </div>
                    <div className="projet sm:col-start-4 sm:col-end-8 sm:row-start-[7] sm:row-end-[11] overflow-hidden flex items-center justify-center relative hoverable-text" data-text="projet5">
                        <img src="./img/works/3.jpg" alt="" className="object-cover object-center h-full w-full absolute"/>
                    </div>
                    <div className="projet sm:col-start-8 sm:col-end-11 sm:row-start-6 sm:row-end-[11] overflow-hidden flex items-center justify-center relative hoverable-text" data-text="projet6">
                        <img src="./img/works/4.jpg" alt="" className="object-cover object-center h-full w-full absolute"/>
                    </div>
                    
                </div>

                <div className="title-section-home-reverse">
                    <h3>Projets</h3>
                </div>
            </section>

            <section className="contact-area border-b border-solid border-black lg:min-h-screen  min-h-[500px] h-fit sm:grid grid-cols-home-grid block">
                <div className="title-section-home">
                    <h3>Contact</h3>
                </div>
                <div className=" flex">
                    <div className="text-container lg:w-2/3 h-full sm:pt-[10vw] sm:pr-[30px] sm:pb-[5vw] sm:pl-[10vw] sm:w-3/4 w-full py-[80px] px-[20px]">
                        <h3 className="title-section-home-mobile">Contact</h3>
                        <ContactForm />
                    </div>

                    <div className="img-container bg-[url('../public/img/contact.png')] bg-cover bg-center w-1/3 h-full lg:block hidden" ></div>
                </div>
            </section>

            
        </>
    )
}