import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Marie-Laure</title>
                <meta name="description" content="Generated by create next app"/>
               
            </Head>
            <header className='header-home'>
            <div className="title-page-home px-[2vw] h-full">
                <div className="wrapper">
                    <h2 className="first-name">Marie-Laure</h2>
                    <h1>Développeuse web</h1>
                    <h2 className="last-name">Edjour</h2>
                </div>
            </div>
        </header>

        <section className="about-us-area">
            <div className="title-section-home">
                <h3>A propos</h3>
            </div>
            <div className="container">
                <h2>Développeuse web</h2>
                <p className="content">Lorem ipsum dolor sit amet consectetur. Lectus nulla sagittis sed vestibulum et eget suspendisse pellentesque. Vulputate quam sit habitant molestie sem tempus velit elit arcu. Velit purus est adipiscing accumsan mauris nulla sollicitudin ac nunc.</p>
                <p className="content">Felis dignissim tortor justo convallis tincidunt amet tincidunt risus non. Purus mi phasellus lobortis ornare. Odio sem fermentum vel risus nec sed. Hac massa diam tempus aenean donec nibh.</p>

                <div className="skills">
                    <strong>HTML - CSS - SASS</strong>
                    <strong>Javascript - JQuery</strong>
                    <strong>PHP - Laravel - MySQL</strong>
                </div>


            </div>
        </section>
        
        <section className="contact-area">
                
                <div className="container">
                    <p className="content">Lorem ipsum dolor sit amet consectetur. Lectus nulla sagittis sed vestibulum et eget suspendisse pellentesque. </p>
                    
                    <form action="" method="post">
                        <div>
                            <input type="text" id="name" name="name"/>
                            <input type="text" id="email" name="email"/>
                        </div>
                    </form>


                </div>

                <div className="title-section-home-reverse">
                    <h3>Projets</h3>
                </div>
            </section>

            <section className="contact-area">
                <div className="title-section-home">
                    <h3>Contact</h3>
                </div>
                <div className="container">
                    <p className="content">Lorem ipsum dolor sit amet consectetur. Lectus nulla sagittis sed vestibulum et eget suspendisse pellentesque. </p>
                    
                    <form action="" method="post">
                        <div>
                            <input type="text" id="name" name="name"/>
                            <input type="text" id="email" name="email"/>
                        </div>
                    </form>


                </div>
            </section>
        </>
    )
}